#!/usr/bin/python3
# Copyright Peter Csaszar (Császár Péter) 2021 <csjpeter@gmail.com>

import sys
if __file__ not in sys.argv[0] :
	print (__file__ + " should not be imported but executed directly")
	sys.exit(1)

import json
import time
import datetime
import subprocess
import fcntl
import os
import re
import getopt
import libvb

class Config : #{{{
	sourceVmName = None
	vmNames = []

	def __init__(this) : #{{{
		pass
		#}}}
#}}}

config = Config()

def printHelp() : #{{{
	print ("Usage: " + sys.argv[0] + """ <--source=sourcevmname> <--name=vmnameprefix> [options]

Parameters:
	-h, --help             : shows this screen
	--source=              : name of the vbox to clone
	--name=                : name (or prefix) for the vbox to be created
	--range=               : enumeration of numbers and ranges appended
	                         to the name prefix for the new clones

Example:
	""" + sys.argv[0] + """ --source=ubuntu20.04 --name=newubuntu --range=1,5-7,15

	The above will create hosts :
	newubuntu1, newubuntu5, newubuntu6, newubuntu7, newubuntu15
""")
#}}}

def parseArgs() : #{{{
	try:
		opts, args = getopt.getopt(sys.argv[1:],
				"hx:x:x:", [
					"help",
					"source=",
					"name=",
					"range="
					])
	except getopt.GetoptError :
		printHelp()
		print("Invalid command line arguments received.")
		sys.exit(2)

	vmNamePrefix = None

	for opt, arg in opts :
		if opt in ("-h", "--help") :
			printHelp()
			sys.exit(0)
		elif opt in ("--source") :
			config.sourceVmName = arg
		elif opt in ("--name") :
			vmNamePrefix = arg

	if config.sourceVmName is None :
		printHelp()
		print("Source vm name have to be specified on the commandline.")
		sys.exit(2)

	if vmNamePrefix is None :
		printHelp()
		print("New vm name have to be specified on the commandline.")
		sys.exit(2)

	config.vmNames = libvb.parseVmNames(opts)
#}}}

parseArgs()

for vmName,vmId in config.vmNames :
	libvb.clonevm(config.sourceVmName, vmName)

